kanban/urls.py
from django.contrib import admin
from django.urls import path
from kanban import views

app_name = 'kanban'
urlpatterns = [
  path('home/', views.KanbanView.as_view(), name='home'),

  path('task_index/', views.TaskListView.as_view(), name='task_index'),
  path('task_create/', views.TaskCreateView.as_view(), name='task_create'),
  path('task_update/<uuid:pk>', views.TaskUpdateView.as_view(), name='task_update'),
  path('task_delete/<uuid:pk>', views.TaskDeleteView.as_view(), name='task_delete'),

  path('diary_index/', views.DiaryListView.as_view(), name='diary_index'),
  path('diary_create/', views.DiaryCreateView.as_view(), name='diary_create'),
  path('diary_update/<uuid:pk>', views.DiaryUpdateView.as_view(), name='diary_update'),
  path('diary_delete/<uuid:pk>', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

nabana003/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('kanban/', include('kanban.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import uuid as uuid_lib

# Create your models here.
class CustomUser(AbstractUser):
    class Meta:
        verbose_name_plural = 'CustomUser'

    user_id = models.UUIDField(default=uuid_lib.uuid4, primary_key=True, editable=False)
    

kanban/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 
from datetime import datetime

import uuid as uuid_lib

from accounts.models import CustomUser

# Create your models here.
class Task(models.Model):
  task_id = models.UUIDField(default=uuid_lib.uuid4, primary_key=True, editable=False)
  user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

  title = models.CharField(null=False, max_length=50)
  deadline = models.DateField()
  status = models.BooleanField(default=False)

  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return self.task_id

class Diary(models.Model):
  diary_id = models.UUIDField(default=uuid_lib.uuid4, primary_key=True, editable=False)
  user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

  title = models.CharField(null=False, max_length=50)
  text = models.CharField(null=False, max_length=1000)

  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return self.diary_id

kanban/forms.py
from django import forms
from kanban.models import Task, Diary

class TaskForm(forms.ModelForm):
  class Meta:
    model = Task
    fields = ('title', 'deadline', 'status')

class DiaryForm(forms.ModelForm):
  class Meta:
    model = Diary
    fields = ('title', 'text')

accounts/views.py
from django.shortcuts import render

# Create your views here.

kanban/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from kanban.models import Task, Diary
from kanban.forms import TaskForm, DiaryForm

# Create your views here.
class KanbanView(LoginRequiredMixin, TemplateView):
  template_name = 'kanban/home.html'

class TaskListView(LoginRequiredMixin, ListView):
  model = Task
  template_name = 'kanban/task_index.html'
  paginate_by = 20

class TaskCreateView(LoginRequiredMixin, CreateView):
  model = Task
  form_class = TaskForm
  template_name = "kanban/task_create.html"
  success_url = "/kanban/task_index"

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class TaskUpdateView(LoginRequiredMixin, UpdateView):
  model = Task
  form_class = TaskForm
  template_name = "kanban/task_update.html"
  success_url = "/kanban/task_index"

class TaskDeleteView(LoginRequiredMixin, DeleteView):
  model = Task
  form_class = TaskForm
  success_url = "/kanban/task_index"

  def delete(self, request, *args, **kwargs):
    result = super().delete(request, *args, **kwargs)
    messages.success(self.request, "タスクを削除しました")
    return result

class DiaryListView(LoginRequiredMixin, ListView):
  model = Diary
  template_name = 'kanban/diary_index.html'
  paginate_by = 20

class DiaryCreateView(LoginRequiredMixin, CreateView):
  model = Diary
  form_class = DiaryForm
  template_name = "kanban/diary_create.html"
  success_url = "/kanban/diary_index"

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class DiaryUpdateView(LoginRequiredMixin, UpdateView):
  model = Diary
  form_class = DiaryForm
  template_name = "kanban/diary_update.html"
  success_url = "/kanban/diary_index"

class DiaryDeleteView(LoginRequiredMixin, DeleteView):
  model = Diary
  form_class = DiaryForm
  success_url = "/kanban/diary_index"

  def delete(self, request, *args, **kwargs):
    result = super().delete(request, *args, **kwargs)
    messages.success(self.request, "日記を削除しました")
    return result

kanban/templates/kanban/base.html
<!DOCTYPE html>
<html lang="ja">
  {% load static %}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
      <a class="navbar-brand" href="">KANBAN</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Todo</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="{% url 'kanban:task_index' %}">一覧</a>
              <a class="dropdown-item" href="{% url 'kanban:task_create' %}">新規登録</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dairy</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="{% url 'kanban:diary_index' %}">一覧</a>
              <a class="dropdown-item" href="{% url 'kanban:diary_create' %}">新規登録</a>
            </div>
          </li>
        </ul>

        <a class="ml-2 btn btn-outline-info" href="{% url 'account_logout' %}"　>ログアウト</a>
      </div>
    </nav>

    {% if messages %}
    <div class="container">
      <ul class="messages_ul">
        {% for message in messages %}
          <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    <footer th:fragment="footer">
      <div class="container mb-5">
        <meta charset="utf-8"/>
        <div class="container text-center">
          <!-- ナビゲーション -->
          <ul class="nav justify-content-center mb-3">
            <li class="nav-item">
              <a class="nav-link" href="">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Menu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Information</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Contact</a>
            </li>
          </ul>
          <!-- /ナビゲーション -->
        <div style="text-align:center">©2021年 | takafumi nishiwaki</div>
      </div>
    </footer>
  </body>
</html>

kanban/templates/kanban/diary_create.html
{% extends "kanban/base.html" %}
{% block title %}diary_index{% endblock title %}
{% block content %}

<!DOCTYPE html>
<html lang="ja">
  <div class="container">
    <head>
      <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
      {% load static %}
      <title>diary</title>
    </head>
    <body>
      <form action="{% url 'kanban:diary_create' %}" method="POST">
        <table class="table">
          {% csrf_token %}
          {{ form.as_table}}
        </table>
        <input class="btn btn-outline-info btn-block text-nowrap" type="submit" value="登録" onclick='return confirm(" 登録しますか？");'>
      </form>
    </body>
  </div>
</html>

{% endblock %}

kanban/templates/kanban/diary_index.html
{% extends "kanban/base.html" %}
{% block title %}diary_index{% endblock title %}
{% block content %}

<!DOCTYPE html>
<html>
  <body>
    <head>
      <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
      {% load static %}
      <title>diary</title>
    </head>
    <div class="container">
      <div class="text-center">
        <table border="1">
          <tr>
            <th>title</th>
            <th>text</th>
            <th></th>
            <th></th>
          </tr>
          {% for diary in object_list %}
          <tr>
            <td>{{ diary.title }}</td>
            <td>{{ diary.text }}</td>
            <th><a href="{% url 'kanban:diary_update' diary.diary_id %}" class="btn btn-outline-secondary btn-sm text-nowrap">更新</a></th>
            <form action="{% url 'kanban:diary_delete' diary.diary_id %}" method="POST">
              {% csrf_token %}
              <td><input type='submit' value='削除' class="btn btn-outline-danger btn-sm text-nowrap" onclick='return confirm("本当に削除しますか？");'></td>
            </form>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </body>
</html>

{% endblock %}

kanban/templates/kanban/diary_update.html
{% extends "kanban/base.html" %}
{% block title %}diary_index{% endblock title %}
{% block content %}

<!DOCTYPE html>
<html lang="ja">
  <div class="container">
    <head>
      <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
      {% load static %}
      <title>diary</title>
    </head>
    <body>
      <form action="{% url 'kanban:diary_update' diary.diary_id %}" method="POST">
        <table class="table">
          {% csrf_token %}
          {{ form.as_table}}
        </table>
        <input class="btn btn-outline-info btn-block text-nowrap" type="submit" value="更新" onclick='return confirm(" 更新しますか？");'>
      </form>
    </body>
  </div>
</html>

{% endblock %}

kanban/templates/kanban/home.html
{% extends "kanban/base.html" %}
{% block title %}task_index{% endblock title %}
{% block content %}
<!DOCTYPE html>
<html>
  <body>
    <div class="container">
      <div class="text-center">
        <p>Hello, World</p>
      </div>
    </div>
  </body>
</html>

{% endblock %}

kanban/templates/kanban/task_create.html
<!DOCTYPE html>
<html lang="ja">
  <div class="container">
    <head>
      <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
      {% load static %}
      <title>anime</title>
    </head>
    <body>
      <form action="{% url 'kanban:task_create' %}" method="POST">
        <table class="table">
          {% csrf_token %}
          {{ form.as_table}}
        </table>
        <input class="btn btn-outline-info btn-block text-nowrap" type="submit" value="登録" onclick='return confirm(" 登録しますか？");'>
      </form>
    </body>
  </div>
</html>

kanban/templates/kanban/task_index.html
{% extends "kanban/base.html" %}
{% block title %}task_index{% endblock title %}
{% block content %}

<!DOCTYPE html>
<html>
  <body>
    <div class="container">
      <table border="1">
        <tr>
          <th>name</th>
          <th>deadline</th>
          <th>done</th>
          <th>created_at</th>
          <th>updated_at</th>
        </tr>
        {% for task in object_list %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.done }}</td>
          <td>{{ task.created_at }}</td>
          <td>{{ task.updated_at }}</td>
          <th><a href="{% url 'kanban:task_update' task.task_id %}" class="btn btn-outline-secondary btn-sm text-nowrap">更新</a></th>
          <form action="{% url 'kanban:task_delete' task.task_id %}" method="POST">
            {% csrf_token %}
            <td><input type='submit' value='削除' class="btn btn-outline-danger btn-sm text-nowrap" onclick='return confirm("本当に削除しますか？");'></td>
          </form>
        </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>

{% endblock %}

kanban/templates/kanban/task_update.html
{% extends "kanban/base.html" %}
{% block title %}task_index{% endblock title %}
{% block content %}

<!DOCTYPE html>
<html lang="ja">
  <div class="container">
    <head>
      <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
      {% load static %}
      <title>task</title>
    </head>
    <body>
      <form action="{% url 'kanban:task_update' task.task_id %}" method="POST">
        <table class="table">
          {% csrf_token %}
          {{ form.as_table}}
        </table>
        <input class="btn btn-outline-info btn-block text-nowrap" type="submit" value="更新" onclick='return confirm(" 更新しますか？");'>
      </form>
    </body>
  </div>
</html>

{% endblock %}